### ISSUE TITLE
About  Aggregation Module And Affinity Loss

### ISSUE THREAD

**Issue by JialeTao** [ycszen/ContextPrior#1]
Hi, first congratulations for the good work. And I have some problems in reading your paper. 

1. In aggregation module, depth-wise separable convolutions is used. To my knowleadge, depth-wise separable convolution does not change the channel of input features while it is changed from $C_0$ to $C_1$ in paper. How it is implemented?

2. Does the gradient of affinity loss backward to segmentation backbone? Or only backward to context prior layer?

3. Noted that an ideal affinity map is used as a supervision for context prior map, how about directly applying ideal affinity map for constructing the concatenated feature? And thus context prior layer can be needless?

Thanks.

**Comment by Mayy1994** [comment]
Hi, I just read this paper and the following is my understanding.

1. Maybe the authors changed the number of channels by using 1x1 Conv after depth-wise separable convolutions.
2. Normally, the gradient should backpropagate to the segmentation backbone.
3. For validation and testing, there is no ideal affinity map. Hence, context prior is necessary.

**Comment by yu-changqian** [comment]
Thanks for your attention. 
1. In Fig.4 (a) of the paper, the Aggregation Module has one 3x3 conv and two asymmetric fully separable convs. The first 3x3 conv can reduce the channel dimension.
2. The gradient should back-propagate to the segmentation backbone.
3. The ideal affinity map is constructed from the Ground Truth. However, in the inference phase, we can not obtain the Ground Truth to construct the ideal affinity map. Therefore, we design a Context Prior Layer to mimic and approach the ideal affinity map.

**Comment by JialeTao** [comment]
> Hi, I just read this paper and the following is my understanding.
> 
> 1. Maybe the authors changed the number of channels by using 1x1 Conv after depth-wise separable convolutions.
> 2. Normally, the gradient should backpropagate to the segmentation backbone.
> 3. For validation and testing, there is no ideal affinity map. Hence, context prior is necessary.

Thanks very much.  The author just answered the first question and I did not notice the 3 by 3 convolution before the fully separation convolution branch.

**Comment by JialeTao** [comment]
> Thanks for your attention.
> 
> 1. In Fig.4 (a) of the paper, the Aggregation Module has one 3x3 conv and two asymmetric fully separable convs. The first 3x3 conv can reduce the channel dimension.
> 2. The gradient should back-propagate to the segmentation backbone.
> 3. The ideal affinity map is constructed from the Ground Truth. However, in the inference phase, we can not obtain the Ground Truth to construct the ideal affinity map. Therefore, we design a Context Prior Layer to mimic and approach the ideal affinity map.

Thanks very much! I didn't  notice that before.
