### ISSUE TITLE
如何进行多尺度评估？

### ISSUE THREAD

**Issue by CuberrChen** [ycszen/ContextPrior#13]
您好，最近我在复现您的论文。遇到了一个不太理解的地方，在Aggregation模块以后，接了一个prior_conv，其输出通道数是H*W。是不是说网络的输入大小一开始就需要是一个定值？不然这里的参数一开始没法设定？但设为定值的话，训练我能理解，可以crop到固定大小。然后由于文章中只提及了进行多尺度评估，我不太清楚如何进行。希望您能给我一点建议。

**Comment by lianxxx** [comment]
> 您好，最近我在复现您的论文。遇到了一个不太理解的地方，在Aggregation模块以后，接了一个prior_conv，其输出通道数是H*W。是不是说网络的输入大小一开始就需要是一个定值？不然这里的参数一开始没法设定？但设为定值的话，训练我能理解，可以crop到固定大小。然后由于文章中只提及了进行多尺度评估，我不太清楚如何进行。希望您能给我一点建议。

I had the same question. Did you get an answer? Thank you.
