### ISSUE TITLE
When to release the code?

### ISSUE THREAD

**Issue by purse1996** [ycszen/ContextPrior#7]
I'm very interested in your work. But the code is still not released? So I want to ask when to release the code? Or can you send me a copy?  Thank you very much.

**Comment by yu-changqian** [comment]
Hi, a simple version of the core codes has been released, which is based on mmsegmentation. 
You can integrate the codes into mmseg to run the experiments. 
Recently I am busy with job hunting and PhD thesis. After this period of time, I will release the complete version.
